name: frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+11
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  http: ^0.12.2
  hexcolor: ^2.0.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/circle-arrow-right.png
    - assets/images/verified copy.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
